---
name: concourse

releases:
- name: concourse
  version: latest
- name: garden-runc
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: web
  instances: 1
  vm_type: large
  vm_extensions:
  - web_load_balancer
  stemcell: trusty
  azs: [z1]
  networks: [{name: default}]
  jobs:
  - name: atc
    release: concourse
    properties:
      external_url: https://((web_load_balancer))
      basic_auth_username: atc
      basic_auth_password: ((admin_password))
      postgresql_database: &atc_db atc
      vault:
        path_prefix: /concourse
        url: https://((vault_static_ip_1)):8200  # e.g. http://192.168.10.15:8200
        auth:
          client_token: ((concourse_token))
  - name: tsa
    release: concourse
    properties: {}

- name: db
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: medium
  stemcell: trusty
  # replace with a disk type from your BOSH Director's cloud config
  persistent_disk_type: large
  azs: [z1]
  networks: [{name: default}]
  jobs:
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: *atc_db
        # make up a role and password
        role: atc
        password: ((db_password))

- name: worker
  instances: 2
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: large
  stemcell: trusty
  azs: [z1]
  networks: [{name: default}]
  jobs:
  - name: groundcrew
    release: concourse
    properties: {}
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

variables:
variables:
- name: admin_password
  type: password
- name: db_password
  type: password
