- type: replace
  path: /vm_extensions?
  value:
  - name: web_load_balancer
    cloud_properties:
      elbs:
      - ((web_load_balancer))
  - name: kibana_load_balancer
    cloud_properties:
      elbs:
      - ((kibana_load_balancer))
