name: logsearch
releases:
- name: logsearch
  version: latest
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest
instance_groups:
- name: elasticsearch_master
  instances: 1
  vm_type: medium
  stemcell: trusty
  azs: [z1]
  networks:
  - name: default
  persistent_disk_type: large
  jobs:
  - name: elasticsearch
    consumes:
      elasticsearch: {from: elasticsearch_master}
    provides:
      elasticsearch: {as: elasticsearch_master}
    release: logsearch
  - name: cerebro
    consumes:
      elasticsearch: {from: elasticsearch_master}
    release: logsearch
  properties:
      elasticsearch:
        node:
          allow_master: true
          allow_data: false
      cerebro:
        secret: secret
      syslog_forwarder:
        config:
        - {service: elasticsearch, file: /var/vcap/sys/log/elasticsearch/elasticsearch.stdout.log}
        - {service: elasticsearch, file: /var/vcap/sys/log/elasticsearch/elasticsearch.stderr.log}
# - name: cluster_monitor
#   instances: 1
#   vm_type: medium
#   stemcell: trusty
#   azs: [z1]
#   networks:
#   - name: default
#   persistent_disk_type: medium
#   jobs:
#   - name: ingestor_syslog
#     release: logsearch
#   - name: elasticsearch
#     consumes:
#       elasticsearch: {from: elasticsearch_master}
#     release: logsearch
#   - name: elasticsearch_config
#     consumes:
#       elasticsearch: {from: elasticsearch_master}
#     release: logsearch
#   - name: curator
#     consumes:
#       elasticsearch: {from: elasticsearch_master}
#     release: logsearch
#   - name: kibana
#     consumes:
#       elasticsearch: {from: elasticsearch_master}
#     release: logsearch
#   properties:
#     kibana:
#       port: 5601
#       elasticsearch:
#         host: 127.0.0.1
#         port: 9200
#       memory_limit: 30
#       wait_for_templates: [shards-and-replicas]
#     elasticsearch:
#       master_hosts: [127.0.0.1]
#       cluster_name: monitor
#       node:
#         allow_master: true
#         allow_data: true
#     redis:
#       host: 127.0.0.1
#       maxmemory: 10
#     curator:
#       elasticsearch:
#         host: 127.0.0.1
#         port: 9200
#       purge_logs:
#         retention_period: 7
#     elasticsearch_config:
#       elasticsearch:
#         host: 127.0.0.1
#         port: 9200
#       index_prefix: "logstash-"
#       templates:
#         - shards-and-replicas: "{ \"template\" : \"logstash-*\", \"order\" : 100, \"settings\" : { \"number_of_shards\" : 1, \"number_of_replicas\" : 0 } }"
#         - index-settings: /var/vcap/jobs/elasticsearch_config/index-templates/index-settings.json
#         - index-mappings: /var/vcap/jobs/elasticsearch_config/index-templates/index-mappings.json
#     logstash_parser:
#       logstash_parser.elasticsearch.index: "logstash-%{+YYYY.MM.dd}"
#       filters:
#       - monitor: /var/vcap/packages/logsearch-config/logstash-filters-monitor.conf
#     nats_to_syslog:
#       debug: true
#     logstash_ingestor:
#       syslog:
#         port: 5514
# - name: maintenance
#   instances: 1
#   vm_type: medium
#   stemcell: trusty
#   azs: [z1]
#   networks:
#   - name: default
#   jobs:
#   - name: elasticsearch_config
#     consumes:
#       elasticsearch: {from: elasticsearch_master}
#     release: logsearch
#   - name: curator
#     consumes:
#       elasticsearch: {from: elasticsearch_master}
#     release: logsearch
- name: elasticsearch_data
  instances: 2
  vm_type: large
  stemcell: trusty
  azs: [z1]
  networks:
  - name: default
  persistent_disk_type: large
  jobs:
  - name: elasticsearch
    consumes:
      elasticsearch: {from: elasticsearch_master}
    release: logsearch
  properties:
    elasticsearch:
      node:
        allow_data: true
        allow_master: false
- name: kibana
  instances: 1
  vm_type: medium
  vm_extensions:
  - kibana_load_balancer
  stemcell: trusty
  azs: [z1]
  networks:
  - name: default
  jobs:
  - consumes:
      elasticsearch: {from: elasticsearch_master}
    name: kibana
    release: logsearch
  - consumes:
      syslog_forwarder: nil
    name: syslog_forwarder
    release: logsearch
  - consumes:
      elasticsearch: {from: elasticsearch_master}
    name: elasticsearch
    release: logsearch
- name: ingestor
  instances: 1
  vm_type: large
  stemcell: trusty
  azs: [z1]
  networks:
  - name: default
  persistent_disk_type: large
  jobs:
  - consumes:
      elasticsearch: {from: elasticsearch_master}
    name: elasticsearch
    release: logsearch
  - name: ingestor_syslog
    release: logsearch
  properties:
    logstash_ingestor:
      debug: false

properties:
  curator:
    purge_logs:
      retention_period: 30
      unit: days
  elasticsearch:
    cluster_name: logsearch
  elasticsearch_config:
    templates:
    - shards-and-replicas: /var/vcap/jobs/elasticsearch_config/index-templates/shards-and-replicas.json
    - index-settings: /var/vcap/jobs/elasticsearch_config/index-templates/index-settings.json
    - index-mappings: /var/vcap/jobs/elasticsearch_config/index-templates/index-mappings.json
  logstash_ingestor:
    debug: false
  logstash_parser:
    debug: false
update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_errors: 1
  max_in_flight: 1
  serial: true
  update_watch_time: 5000-600000
