name: logsearch
releases:
- name: logsearch
  version: latest
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest
instance_groups:
- name: elasticsearch_master
  instances: 1
  vm_type: medium
  azs: [z1]
  networks:
  - name: default
  persistent_disk_type: large
  jobs:
  - name: elasticsearch
    consumes:
      elasticsearch: nil
    provides:
      elasticsearch:
        elasticsearch: {as: elasticsearch_master}
    release: logsearch
  - name: cerebro
    consumes:
      elasticsearch: {from: elasticsearch_master}
    release: logsearch
- name: cluster_monitor
  instances: 1
  vm_type: medium
  stemcell: trusty
  azs: [z1]
  networks:
  - name: default
  persistent_disk_type: medium
  jobs:
  - name: ingestor_syslog
    release: logsearch
  - name: elasticsearch
    consumes:
      elasticsearch: {from: elasticsearch_master}
    release: logsearch
  - name: elasticsearch_config
    consumes:
      elasticsearch: {from: elasticsearch_master}
    release: logsearch
  - name: curator
    consumes:
      elasticsearch: {from: elasticsearch_master}
    release: logsearch
  - name: kibana
    consumes:
      elasticsearch: {from: elasticsearch_master}
    release: logsearch
- name: maintenance
  instances: 1
  vm_type: medium
  stemcell: trusty
  azs: [z1]
  networks:
  - name: default
  jobs:
  - name: elasticsearch_config
    consumes:
      elasticsearch: {from: elasticsearch_master}
    release: logsearch
  - name: curator
    consumes:
      elasticsearch: {from: elasticsearch_master}
    release: logsearch
- name: elasticsearch_data
  instances: 2
  vm_type: large
  stemcell: trusty
  azs: [z1]
  networks:
  - name: default
  persistent_disk_type: large
  jobs:
  - name: elasticsearch
    consumes:
      elasticsearch: {from: elasticsearch_master}
    release: logsearch
  properties:
    elasticsearch:
      node:
        allow_data: true
        allow_master: false
- name: kibana
  instances: 1
  vm_type: medium
  stemcell: trusty
  azs: [z1]
  networks:
  - name: default
  jobs:
  - consumes:
      elasticsearch: {from: elasticsearch_master}
    name: kibana
    release: logsearch
  - consumes:
      syslog_forwarder: nil
    name: syslog_forwarder
    release: logsearch
  - consumes:
      elasticsearch: {from: elasticsearch_master}
    name: elasticsearch
    release: logsearch
- name: ingestor
  instances: 1
  vm_type: medium
  stemcell: trusty
  azs: [z1]
  networks:
  - name: default
  persistent_disk_type: large
  jobs:
  - consumes:
      elasticsearch: {from: elasticsearch_master}
    name: elasticsearch
    release: logsearch
  - name: ingestor_syslog
    release: logsearch
  properties:
    logstash_ingestor:
      debug: false
# - instances: 1
#   name: ingestor-bosh-nats
#   vm_type: medium
#   stemcell: trusty
#   azs: [z1]
#   networks:
#   - name: default
#     static_ips:
#     - 192.168.1.100
#   properties:
#     logstash_ingestor:
#       syslog:
#         port: 5514
#     syslog_forwarder:
#       config:
#       - file: /var/vcap/sys/log/nats_to_syslog/nats_to_syslog.stdout.log
#         service: nats_to_syslog
#       - file: /var/vcap/sys/log/nats_to_syslog/nats_to_syslog.stderr.log
#         service: nats_to_syslog
#   resource_pool: ingestor
#   templates:
#   - name: ingestor_syslog
#     release: logsearch
#   - consumes:
#       syslog_forwarder: nil
#     name: nats_to_syslog
#     release: logsearch
#   - consumes:
#       syslog_forwarder: nil
#     name: syslog_forwarder
#     release: logsearch
# - instances: 1
#   name: ls-router
#   networks:
#   - default:
#     - gateway
#     - dns
#     name: default
#     static_ips:
#     - 192.168.1.105
#   properties:
#     haproxy:
#       cluster_monitor:
#         backend_servers:
#         - 192.168.1.98
#       ingestor:
#         backend_servers:
#         - 192.168.1.97
#       kibana:
#         backend_servers:
#         - 192.168.1.101
#       syslog_server: 192.168.1.98
#   resource_pool: haproxy
#   templates:
#   - consumes:
#       elasticsearch: nil
#       ingestor: nil
#       kibana: nil
#       syslog_forwarder: nil
#     name: haproxy
#     release: logsearch
# - consumes:
#     elasticsearch: nil
#   instances: 1
#   lifecycle: errand
#   name: smoke-tests
#   networks:
#   - name: default
#   properties:
#     smoke_tests:
#       elasticsearch_master:
#         host: 192.168.1.96
#       syslog_ingestor:
#         host: 192.168.1.105
#         port: 5514
#   release: logsearch
#   resource_pool: errand
#   templates:
#   - consumes:
#       elasticsearch: nil
#     name: smoke-tests
#     release: logsearch

properties:
  curator: {}
    purge_logs:
      retention_period: 30
      unit: days
  elasticsearch:
    cluster_name: logsearch
  elasticsearch_config:
    templates:
    - shards-and-replicas: /var/vcap/jobs/elasticsearch_config/index-templates/shards-and-replicas.json
    - index-settings: /var/vcap/jobs/elasticsearch_config/index-templates/index-settings.json
    - index-mappings: /var/vcap/jobs/elasticsearch_config/index-templates/index-mappings.json
  logstash_ingestor:
    debug: false
  logstash_parser:
    debug: false
update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_errors: 1
  max_in_flight: 1
  serial: true
  update_watch_time: 5000-600000
